#include "core/PhotographicDecomposition.h"
#include "core/ScreenedMultigrid.h"
#include "core/SoftPictorialPlates.h"
#include "core/PigmentPhase33.h"

#include <cmath>
#include <iostream>

namespace {
int failures=0;
void check(bool v,const char*m){if(!v){++failures;std::cerr<<"FAIL: "<<m<<'\n';}}

pigment::OwnedYabPlanes fixture(pigment::RectI b){pigment::OwnedYabPlanes o(b);auto v=o.view();for(int y=b.y1;y<b.y2;++y)for(int x=b.x1;x<b.x2;++x){float fx=float(x-b.x1)/std::max(1,b.width()-1),fy=float(y-b.y1)/std::max(1,b.height()-1);v.y.at(x,y)=-.2f+2.4f*fx+.08f*std::sin(1.7f*x);v.a.at(x,y)=.3f*(fy-.5f);v.b.at(x,y)=fx<.5f?-.25f:.35f;}return o;}

void plates(){pigment::RectI b{0,0,40,28};auto src=fixture(b);const auto source=static_cast<const pigment::OwnedYabPlanes&>(src).view();pigment::SoftPlateConstructionParams p;p.automaticOccupancy=1;p.spatialCoherence=.2f;pigment::OwnedSoftPlateSet a(b),s(b);pigment::buildConvexPalettePlates(source,0.0f,p,a);auto av=static_cast<const pigment::OwnedSoftPlateSet&>(a).view();for(int y=0;y<b.y2;++y)for(int x=0;x<b.x2;++x){float sum=av.base.at(x,y);for(int i=0;i<4;++i)sum+=av.normalized[i].at(x,y);check(std::abs(sum-1)<2e-5f,"automatic memberships sum to one");check(av.base.at(x,y)==0,"full automatic occupancy never falls back from error");}
  p.automaticOccupancy=.6f;pigment::buildSpatialLayerPlates(source,0.0f,p,s);auto sv=static_cast<const pigment::OwnedSoftPlateSet&>(s).view();check(!s.controlVertices().empty(),"spatial layers retain rich control vertices");check(std::abs(sv.base.at(5,5)-.4f)<1e-5f,"automatic base is artist controlled");check(std::isfinite(sv.reconstructionError.at(5,5)),"reconstruction error remains diagnostic");
  pigment::OwnedPlaneMemberships manual(b);pigment::OwnedSoftPlateSet hybrid(b);auto mv=manual.view();for(int y=0;y<b.y2;++y)for(int x=0;x<b.x2;++x){mv.plane[0].at(x,y)=0;mv.plane[1].at(x,y)=0;mv.plane[2].at(x,y)=0;mv.plane[3].at(x,y)=0;mv.base.at(x,y)=1;}pigment::applyHybridPlateGuidance(av,static_cast<const pigment::OwnedPlaneMemberships&>(manual).view(),1,hybrid.view());auto hv=static_cast<const pigment::OwnedSoftPlateSet&>(hybrid).view();check(std::abs(hv.normalized[2].at(10,10)-av.normalized[2].at(10,10))<1e-6f,"empty Hybrid guidance equals automatic");for(int y=0;y<b.y2;++y)for(int x=0;x<b.x2;++x){mv.plane[1].at(x,y)=1;mv.base.at(x,y)=0;}pigment::applyHybridPlateGuidance(av,static_cast<const pigment::OwnedPlaneMemberships&>(manual).view(),1,hybrid.view());check(std::abs(hv.normalized[1].at(10,10)-1)<1e-6f&&hv.base.at(10,10)==0,"strong Hybrid paint locks exactly");
}

void solvers(){pigment::RectI b{0,0,96,48};pigment::OwnedPlane source(b),result(b),conductance(b,1);auto s=source.view();for(int y=0;y<b.y2;++y)for(int x=0;x<b.x2;++x)s.at(x,y)=x<48?0:1;pigment::ScreenedMultigridParams p;p.lambdaX=p.lambdaY=16;float before=0;for(int y=0;y<b.y2;++y)for(int x=0;x<b.x2;++x)before+=s.at(x,y)*s.at(x,y);pigment::solveScreenedMultigrid(static_cast<const pigment::OwnedPlane&>(source).view(),1,1,result.view(),p);float residual=pigment::screenedResidualRms(static_cast<const pigment::OwnedPlane&>(result).view(),static_cast<const pigment::OwnedPlane&>(source).view(),1,1,16,16);check(std::isfinite(residual)&&residual<.02f,"multigrid produces a low finite residual");
  pigment::OwnedPlane conditional(b);pigment::OwnedPlane membership(b,.5f);pigment::conditionalSmoothField(static_cast<const pigment::OwnedPlane&>(source).view(),static_cast<const pigment::OwnedPlane&>(membership).view(),1,0,conditional.view());check(std::abs(conditional.view().at(10,10)-s.at(10,10))<1e-5f&&std::abs(conditional.view().at(80,10)-s.at(80,10))<1e-5f,"conditional WLS does not square membership weighting");
}

void decomposition(){pigment::RectI b{0,0,48,32};auto src=fixture(b);const auto source=static_cast<const pigment::OwnedYabPlanes&>(src).view();pigment::OwnedPlane smooth(b);pigment::sourceSmoothWls(source.y,0.0f,.4f,.8f,{},smooth.view());pigment::PhotographicComponents c(b);pigment::decomposePhotographicLuminance(source.y,static_cast<const pigment::OwnedPlane&>(smooth).view(),0.0f,c);float maxError=0;for(int y=0;y<b.y2;++y)for(int x=0;x<b.x2;++x){float r=c.smooth.view().at(x,y)+c.structure.view().at(x,y)+c.medium.view().at(x,y)+c.fine.view().at(x,y);maxError=std::max(maxError,std::abs(r-source.y.at(x,y)));}check(maxError<2e-5f,"photographic components reconstruct exactly");pigment::OwnedPlane tgv(b);auto d=pigment::tgvRegularizedSmooth(source.y,0.0f,.15f,.8f,{},tgv.view());check(d.tau*d.sigma*d.operatorNormSquaredBound<1,"TGV step sizes satisfy the operator bound");check(d.finite&&std::isfinite(d.finalEnergy)&&d.finalEnergy<=d.initialEnergy*1.1f,"TGV remains finite with bounded energy");
}

void render(){pigment::RectI b{-3,4,21,20};const int stride=b.width()*4+5;std::vector<float>source(size_t(stride)*b.height(),-7),output(source.size(),-9);for(int y=b.y1;y<b.y2;++y)for(int x=b.x1;x<b.x2;++x){size_t i=size_t(y-b.y1)*stride+(x-b.x1)*4;float a=.2f+.8f*float((x-y+31)%11)/10;source[i]=a*(.03f*x+.2f);source[i+1]=a*(.04f*y-.1f);source[i+2]=a*(((x+y)%7==0)?2.5f:.15f);source[i+3]=a;}pigment::IntegratedPigmentParams p;p.comparison=pigment::PigmentComparisonMode::SoftPictorialPlates;p.premultiplied=true;p.veilAmount=0;p.pictorial.localSoftness=0;p.phase33.plates.source=pigment::PlaneSourceMode::AutoConvexPalette;p.phase33.decomposition.smoothSimplification=.2f;p.phase33.transitionSolver=pigment::TransitionSolverMode::MultigridReference;p.structureScale=2;p.boundaryScale=4;p.pictorial.yTransitionWidth=3;p.pictorial.abTransitionWidth=7;pigment::Phase33RenderInputs in{{source.data(),stride,b,4},{output.data(),stride,b,4},b,p,{}};pigment::processPigmentPhase33(in);bool changed=false;for(int y=b.y1;y<b.y2;++y)for(int x=b.x1;x<b.x2;++x){size_t i=size_t(y-b.y1)*stride+(x-b.x1)*4;check(output[i+3]==source[i+3],"Phase 3.3 preserves alpha exactly");check(std::isfinite(output[i])&&std::isfinite(output[i+1])&&std::isfinite(output[i+2]),"Phase 3.3 output is finite");changed|=std::abs(output[i]-source[i])>1e-6f;}check(changed,"Phase 3.3 CPU renderer changes non-identity input");}
}
int main(){plates();solvers();decomposition();render();if(failures)return 1;std::cout<<"All Phase 3.3 core tests passed\n";}
