#include "core/SoftPictorialPlates.h"
#include "core/ScreenedMultigrid.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <numeric>
#include <vector>

namespace pigment {
namespace {
float clamp01(float x) noexcept { return std::max(0.0f, std::min(1.0f, x)); }
float smoothstep(float a,float b,float x) noexcept {float t=clamp01((x-a)/std::max(1e-8f,b-a));return t*t*(3-2*t);}
YabPixel pixel(ConstYabPlanes s,int x,int y) noexcept{return{s.y.at(x,y),s.a.at(x,y),s.b.at(x,y)};}
YabPixel add(YabPixel a,YabPixel b) noexcept{return{a.y+b.y,a.a+b.a,a.b+b.b};}
YabPixel mul(YabPixel a,float s) noexcept{return{a.y*s,a.a*s,a.b*s};}
float distance2(YabPixel a,YabPixel b,float sy,float sc) noexcept {float y=(a.y-b.y)/sy,x=(a.a-b.a)/sc,z=(a.b-b.b)/sc;return y*y+x*x+z*z;}
float median(std::vector<float> v){if(v.empty())return 0;auto m=v.begin()+v.size()/2;std::nth_element(v.begin(),m,v.end());return*m;}
struct FeatureScale{float y=1,c=1;};
FeatureScale featureScale(const std::vector<YabPixel>&v){std::vector<float>ys,as,bs;for(auto p:v){ys.push_back(p.y);as.push_back(p.a);bs.push_back(p.b);}float my=median(ys),ma=median(as),mb=median(bs);for(float&x:ys)x=std::abs(x-my);for(float&x:as)x=std::abs(x-ma);for(float&x:bs)x=std::abs(x-mb);float aa=median(as),bb=median(bs);return{std::max(1e-4f,1.4826f*median(ys)),std::max(1e-4f,1.4826f*std::sqrt(aa*aa+bb*bb))};}

std::array<YabPixel,4> initialPalette(const std::vector<YabPixel>&c,FeatureScale s){
  std::array<YabPixel,4>p{};if(c.empty())return p;auto less=[](auto a,auto b){return a.y<b.y||(a.y==b.y&&(a.a<b.a||(a.a==b.a&&a.b<b.b)));};p[0]=*std::min_element(c.begin(),c.end(),less);p[1]=*std::max_element(c.begin(),c.end(),less);
  auto segment=[&](YabPixel v,YabPixel a,YabPixel b){float dy=(b.y-a.y)/s.y,da=(b.a-a.a)/s.c,db=(b.b-a.b)/s.c;float vy=(v.y-a.y)/s.y,va=(v.a-a.a)/s.c,vb=(v.b-a.b)/s.c;float t=clamp01((vy*dy+va*da+vb*db)/std::max(1e-8f,dy*dy+da*da+db*db));vy-=t*dy;va-=t*da;vb-=t*db;return vy*vy+va*va+vb*vb;};
  float best=-1;for(auto v:c){float d=segment(v,p[0],p[1]);if(d>best){best=d;p[2]=v;}}best=-1;for(auto v:c){float d=std::min({distance2(v,p[0],s.y,s.c),distance2(v,p[1],s.y,s.c),distance2(v,p[2],s.y,s.c)});if(d>best){best=d;p[3]=v;}}return p;
}
bool solveLinear(float a[5][6],int n,float*r){for(int c=0;c<n;++c){int p=c;for(int y=c+1;y<n;++y)if(std::abs(a[y][c])>std::abs(a[p][c]))p=y;if(std::abs(a[p][c])<1e-9f)return false;for(int k=c;k<=n;++k)std::swap(a[p][k],a[c][k]);float inv=1/a[c][c];for(int k=c;k<=n;++k)a[c][k]*=inv;for(int y=0;y<n;++y)if(y!=c){float f=a[y][c];for(int k=c;k<=n;++k)a[y][k]-=f*a[c][k];}}for(int i=0;i<n;++i)r[i]=a[i][n];return true;}
std::array<float,4> convexWeights(YabPixel v,const std::array<YabPixel,4>&p,FeatureScale s,float coherence,float*err=nullptr){
  std::array<float,4>best{};float bestO=std::numeric_limits<float>::infinity(),kappa=.02f+.35f*clamp01(coherence);
  for(int mask=1;mask<16;++mask){int ids[4],m=0;for(int i=0;i<4;++i)if(mask&(1<<i))ids[m++]=i;float a[5][6]{};for(int r=0;r<m;++r)for(int c=0;c<m;++c){auto x=p[ids[r]],y=p[ids[c]];a[r][c]=x.y*y.y/(s.y*s.y)+(x.a*y.a+x.b*y.b)/(s.c*s.c)+(r==c?1e-5f:0);}for(int r=0;r<m;++r){auto x=p[ids[r]];a[r][m]=1;a[r][m+1]=x.y*v.y/(s.y*s.y)+(x.a*v.a+x.b*v.b)/(s.c*s.c)-.5f*kappa*distance2(v,x,s.y,s.c);a[m][r]=1;}a[m][m+1]=1;float q[5]{};if(!solveLinear(a,m+1,q))continue;bool ok=true;for(int i=0;i<m;++i)if(q[i]<-1e-5f)ok=false;if(!ok)continue;std::array<float,4>w{};for(int i=0;i<m;++i)w[ids[i]]=std::max(0.0f,q[i]);float sum=std::accumulate(w.begin(),w.end(),0.0f);if(sum<=1e-8f)continue;for(float&x:w)x/=sum;YabPixel rec{};float compact=0,norm=0;for(int i=0;i<4;++i){rec=add(rec,mul(p[i],w[i]));compact+=w[i]*distance2(v,p[i],s.y,s.c);norm+=w[i]*w[i];}float o=distance2(v,rec,s.y,s.c)+kappa*compact+1e-5f*norm;if(o<bestO){bestO=o;best=w;}}
  if(!std::isfinite(bestO)){best={1,0,0,0};bestO=distance2(v,p[0],s.y,s.c);}if(err)*err=std::sqrt(std::max(0.0f,bestO));return best;
}
std::vector<YabPixel> candidates(ConstYabPlanes s){RectI b=s.y.bounds;int nx=std::min(32,std::max(2,b.width())),ny=std::min(32,std::max(2,b.height()));std::vector<YabPixel>v;for(int j=0;j<ny;++j)for(int i=0;i<nx;++i){int x=b.x1+std::min(b.width()-1,(2*i+1)*b.width()/(2*nx)),y=b.y1+std::min(b.height()-1,(2*j+1)*b.height()/(2*ny));v.push_back(pixel(s,x,y));}return v;}
void finalize(ConstYabPlanes source,FeatureScale scale,const SoftPlateConstructionParams&p,OwnedSoftPlateSet&r,const ExecutionContext&e){auto o=r.view();RectI b=source.y.bounds;float occupancy=clamp01(p.automaticOccupancy);e.parallelRows(b.y1,b.y2,[&](int y0,int y1){for(int y=y0;y<y1;++y)for(int x=b.x1;x<b.x2;++x){float sum=0;for(int i=0;i<4;++i)sum+=std::max(0.0f,o.raw[i].at(x,y));YabPixel rec{};for(int i=0;i<4;++i){float share=std::max(0.0f,o.raw[i].at(x,y))/std::max(1e-8f,sum);o.normalized[i].at(x,y)=occupancy*share;rec=add(rec,mul(r.palette()[i],share));}o.base.at(x,y)=1-occupancy;float er=std::sqrt(distance2(pixel(source,x,y),rec,scale.y,scale.c));o.reconstructionError.at(x,y)=er;o.confidence.at(x,y)=1/(1+er);}});}
}

OwnedSoftPlateSet::OwnedSoftPlateSet(RectI b):raw_{OwnedPlane(b),OwnedPlane(b),OwnedPlane(b),OwnedPlane(b)},normalized_{OwnedPlane(b),OwnedPlane(b),OwnedPlane(b),OwnedPlane(b)},base_(b,1),confidence_(b),reconstructionError_(b){}
SoftPlateSetView OwnedSoftPlateSet::view()noexcept{return{{raw_[0].view(),raw_[1].view(),raw_[2].view(),raw_[3].view()},{normalized_[0].view(),normalized_[1].view(),normalized_[2].view(),normalized_[3].view()},base_.view(),confidence_.view(),reconstructionError_.view(),4};}
ConstSoftPlateSetView OwnedSoftPlateSet::view()const noexcept{return{{raw_[0].view(),raw_[1].view(),raw_[2].view(),raw_[3].view()},{normalized_[0].view(),normalized_[1].view(),normalized_[2].view(),normalized_[3].view()},base_.view(),confidence_.view(),reconstructionError_.view(),4};}

void buildConvexPalettePlates(ConstYabPlanes source,ScalarFieldView,const SoftPlateConstructionParams&p,OwnedSoftPlateSet&r,const ExecutionContext&e){auto c=candidates(source);auto scale=featureScale(c);r.palette()=initialPalette(c,scale);RectI b=source.y.bounds;auto out=r.view();for(int it=0;it<6;++it){std::array<YabPixel,4>s{};std::array<double,4>w{};for(int y=b.y1;y<b.y2;++y)for(int x=b.x1;x<b.x2;++x){auto v=pixel(source,x,y);auto q=convexWeights(v,r.palette(),scale,p.colorCoherence);for(int i=0;i<4;++i){s[i]=add(s[i],mul(v,q[i]));w[i]+=q[i];}}for(int i=0;i<4;++i)if(w[i]>1e-7)r.palette()[i]=mul(s[i],float(1/w[i]));}e.parallelRows(b.y1,b.y2,[&](int y0,int y1){for(int y=y0;y<y1;++y)for(int x=b.x1;x<b.x2;++x){auto q=convexWeights(pixel(source,x,y),r.palette(),scale,p.colorCoherence);for(int i=0;i<4;++i)out.raw[i].at(x,y)=q[i];}});if(p.spatialCoherence>1e-5f){std::array<OwnedPlane,4>sm{OwnedPlane(b),OwnedPlane(b),OwnedPlane(b),OwnedPlane(b)};for(int i=0;i<4;++i){ScreenedMultigridParams mg;mg.lambdaX=mg.lambdaY=.25f+3.75f*p.spatialCoherence*p.spatialCoherence;mg.vCycles=2;solveScreenedMultigrid(ConstFloatPlaneView{out.raw[i].data,out.raw[i].rowStride,b},1,1,sm[i].view(),mg,e);for(int y=b.y1;y<b.y2;++y)for(int x=b.x1;x<b.x2;++x)out.raw[i].at(x,y)=sm[i].view().at(x,y);}}finalize(source,scale,p,r,e);}

void buildSpatialLayerPlates(ConstYabPlanes source,ScalarFieldView structure,const SoftPlateConstructionParams&p,OwnedSoftPlateSet&r,const ExecutionContext&e){RectI b=source.y.bounds;int spacing=std::max(4,int(std::round(8+88*clamp01(p.spatialCoherence))));int nx=std::max(2,(b.width()+spacing-1)/spacing+1),ny=std::max(2,(b.height()+spacing-1)/spacing+1);auto&vs=r.controlVertices();vs.clear();vs.resize(size_t(nx)*ny);std::vector<YabPixel>colors;for(int j=0;j<ny;++j)for(int i=0;i<nx;++i){auto&v=vs[size_t(j)*nx+i];v.x=float(std::min(b.x2-1,b.x1+i*spacing));v.y=float(std::min(b.y2-1,b.y1+j*spacing));YabPixel sum{};float sw=0;for(int oy=-2;oy<=2;++oy)for(int ox=-2;ox<=2;++ox){int x=std::max(b.x1,std::min(b.x2-1,int(v.x)+ox)),y=std::max(b.y1,std::min(b.y2-1,int(v.y)+oy));float w=1-clamp01(structure.at(x,y));sum=add(sum,mul(pixel(source,x,y),w));sw+=w;}v.color=mul(sum,1/std::max(1e-6f,sw));colors.push_back(v.color);}auto scale=featureScale(colors);r.palette()=initialPalette(colors,scale);
  for(int it=0;it<6;++it){std::vector<std::array<float,4>>next(vs.size());std::array<YabPixel,4>s{};std::array<double,4>w{};for(int j=0;j<ny;++j)for(int i=0;i<nx;++i){int n=j*nx+i;auto q=convexWeights(vs[n].color,r.palette(),scale,p.colorCoherence);std::array<float,4>neighbor{};float count=0;const int dx[4]={-1,1,0,0},dy[4]={0,0,-1,1};for(int d=0;d<4;++d){int xx=i+dx[d],yy=j+dy[d];if(it&&xx>=0&&xx<nx&&yy>=0&&yy<ny){for(int k=0;k<4;++k)neighbor[k]+=vs[yy*nx+xx].weights[k];++count;}}if(count)for(int k=0;k<4;++k)q[k]=(q[k]+p.spatialCoherence*neighbor[k]/count)/(1+p.spatialCoherence);next[n]=q;}for(size_t n=0;n<vs.size();++n){vs[n].weights=next[n];for(int k=0;k<4;++k){s[k]=add(s[k],mul(vs[n].color,next[n][k]));w[k]+=next[n][k];}}for(int k=0;k<4;++k)if(w[k]>1e-7)r.palette()[k]=mul(s[k],float(1/w[k]));}
  auto out=r.view();e.parallelRows(b.y1,b.y2,[&](int y0,int y1){for(int y=y0;y<y1;++y)for(int x=b.x1;x<b.x2;++x){float gx=float(x-b.x1)/spacing,gy=float(y-b.y1)/spacing;int ix=std::min(nx-2,std::max(0,int(std::floor(gx)))),iy=std::min(ny-2,std::max(0,int(std::floor(gy))));float tx=clamp01(gx-ix),ty=clamp01(gy-iy);int ids[3];float bw[3];if(tx+ty<=1){ids[0]=iy*nx+ix;ids[1]=ids[0]+1;ids[2]=(iy+1)*nx+ix;bw[0]=1-tx-ty;bw[1]=tx;bw[2]=ty;}else{ids[0]=(iy+1)*nx+ix+1;ids[1]=(iy+1)*nx+ix;ids[2]=iy*nx+ix+1;bw[0]=tx+ty-1;bw[1]=1-tx;bw[2]=1-ty;}for(int k=0;k<4;++k){float q=0;for(int n=0;n<3;++n)q+=bw[n]*vs[ids[n]].weights[k];out.raw[k].at(x,y)=q;}}});finalize(source,scale,p,r,e);}

void applyHybridPlateGuidance(ConstSoftPlateSetView a,ConstPlaneMembershipPlanes m,float guidance,SoftPlateSetView d,const ExecutionContext&e){RectI b=d.base.bounds;float H=clamp01(guidance);e.parallelRows(b.y1,b.y2,[&](int y0,int y1){for(int y=y0;y<y1;++y)for(int x=b.x1;x<b.x2;++x){float om=clamp01(1-m.base.at(x,y)),oa=clamp01(1-a.base.at(x,y)),h=H*om,maxRaw=0;for(int i=0;i<4;++i)maxRaw=std::max(maxRaw,m.plane[i].at(x,y));float lock=H*smoothstep(.9f,.99f,maxRaw),og=(1-h)*oa+h*om,sum=0;for(int i=0;i<4;++i){float ah=a.normalized[i].at(x,y)/std::max(oa,1e-8f),mh=om>1e-8f?m.plane[i].at(x,y)/om:0,u=(1-h)*ah+h*mh,p=(1-lock)*og*u+lock*m.plane[i].at(x,y);d.raw[i].at(x,y)=p;sum+=p;}float base=(1-lock)*(1-og)+lock*m.base.at(x,y),total=std::max(1e-8f,sum+base);for(int i=0;i<4;++i)d.normalized[i].at(x,y)=d.raw[i].at(x,y)/total;d.base.at(x,y)=base/total;d.confidence.at(x,y)=a.confidence.at(x,y);d.reconstructionError.at(x,y)=a.reconstructionError.at(x,y);}});}
}  // namespace pigment
